#!/bin/bash
#run casscf(6,6) E calculations for 6 H atoms in a planar pyramid of isosceles triangles, distorting length of third side relative to others
#uses program writecmatrix.f to write the input file 'H6.com' for a given side length
# extracts the resulting E from the output file 'H6.log'  and writes to fort.12

declare -i linenum
declare -i n=1
declare -i mult=1
declare -x y=0.25
declare -x stepsize=0.025
declare -i nsteps=130
declare -i step=1
declare -i count
declare -a linnums
declare -a eigenvals
declare -x rrt3=0.57735027 #reciprocal of sqrt of 3 = (3)^(-1/2)
comfile='h4.com'
logfile='h4.log'
chkfile='h4.chk'

echo '#HF isntabilities: hessian eigenvalues' > fort.12
echo '#y','rrhf','crhf','ruhf' >> fort.12
while [ $step -le $nsteps ]; do
#create input file for gaussian
	echo $chkfile > $comfile
	echo ' ' >> $comfile
	echo '#t rhf/gen scf(tight,novaracc,noincfock) geom=nocrowd stable(crhf) test' >> $comfile
	echo ' ' >> $comfile
        x=$(bc <<< "scale=6; $rrt3 / $y")
        echo 'scf stability calculation for a rhombic configuration of 4 H atoms (made up of 2 iscosceles triangles)' >> $comfile
        echo ' ' >> $comfile
        echo '0 '$mult >> $comfile
        echo 'H 0.0 0.0 '$y >> $comfile
        echo 'H '$x' 0.0 0.0' >> $comfile
        echo 'H -'$x' 0.0 0.0' >> $comfile
        echo 'H 0.0 0.0 -'$y >> $comfile
        echo ' ' >> $comfile
        echo '@H.gbs' >> $comfile
        echo ' ' >> $comfile
#grab eigenvals from ouput
	g09 < $comfile >& $logfile
#grab eigenvals from ouput
#rrhf
        stabstring=$(grep -E 'Internal RHF' $logfile)
        rrhf=$(echo $stabstring | grep -o -E '\-*[0-9]+\.[0-9]*')
        linenum=$linenum+1
#crhf
        stabstring=$(grep -E 'RRHF.*CRHF' $logfile)
        crhf=$(echo $stabstring | grep -o -E '\-*[0-9]+\.[0-9]*')
#ruhf
        stabstring=$(grep -E 'RRHF.*RUHF' $logfile)
        ruhf=$(echo $stabstring | grep -o -E '\-*[0-9]+\.[0-9]*')
#write to file stable
        echo $y $rrhf $crhf $ruhf >> fort.12
	y=$(echo $y + $stepsize | bc)
	step=$step+1
done

