#!/bin/bash
#run casscf(6,6) E calculations for 3 H atoms in an isosceles triangle, distorting length of third side relative to others
#uses program writecmatrix.f to write the input file 'H3.com' for a given side length
# extracts the resulting E from the output file 'H3.log'  and writes to fort.12

declare -i numsteps=69
declare -i counter=1
declare -x stepsize=0.05
declare -i linenum
declare -x y=0.5
while [ $counter -le $numsteps ]; do
	echo $y > writecmatrix.inp
	./writecmatrix < writecmatrix.inp
	g09 < H3.com >& H3.log
	linenumstring=$(grep -n '... Do an extra-iteration for final printing.' H3.log)
	linenum=$(echo $linenumstring | grep -o -E '[0-9]+')
	let linenum=$linenum-1
	estring=$(head -$linenum H3.log | tail -1)
	e=$(echo $estring | grep -o -E '\-*[0-9]+\.[0-9]+\s')
	echo $y $e >> fort.12
 	y=$(echo $y + $stepsize | bc)
	counter+=1
done
