#!/bin/bash

declare -i number

numberstring=$(grep -n 'Summary' D4model.log)
number=$(echo $numberstring | grep -o -E '[0-9]+')
number=$number+62
echo '#n,r,scf,mp2,mp3' > fort.12
head -$number D4model.log | tail -60 > fort.12
