#!/bin/csh

f95 -c Precision.f90 Constants.f90 HamiltonianData.f90 IO.f90
f95 -o xCode Precision.o Constants.o HamiltonianData.o IO.o ObaraSaika.f90 DoIntegrals.f90 DIIS.f90 UHF.f90 UHFWrap.f90 IntTrans.f90 IndexCI.f90 Hamiltonian.f90 CI.f90 Wrappers.f90 AllCase.f90 Functions.f90 Main.f90 -L . -l AllLinAlgF95

rm *.o *.mod *.f

