#!/bin/bash
#run rhf stability calculation using gaussian
#writes rhf E, rhf HOMO-1 -> LUMO+1 E's, RRHF,CRHF,RUHF hessian eigenvalues

declare -i linenum
declare -x step=0.0001 #in alpha (degrees), not y
declare -i keepgoing=1
#vars for distortion param 
declare -x alpha=70.658680615
declare -x alphaf=70.658680616
declare -x y
declare -a sigpts=( 19.34 37.44 52.56 70.658 )
declare -x tinystep=0.0000000001
declare -x dist
declare -i gt0
declare -i usefinemesh
#output files and gaussian files
comfile='h10.com'
logfile='h10.log'
hessfile='h10hess'
mofile='h10MOE'
efile='h10RHFE'

mkdir com log

cp guess.chk h10.chk
#loop for highsymm->yi
while [ $keepgoing -eq 1 ]; do
#create input file for gaussian
	echo $alpha > tmp
        ./writez < tmp > $comfile
	y=$(grep -o -E '\-*[0-9]+\.[0-9]*' fort.8)
	rm tmp fort.8
#run gaussian
        g09 < $comfile >& $logfile
#grab eigenvals from ouput
#rrhf
        stabstring=$(grep -E 'Internal RHF' $logfile)
        rrhf=$(echo $stabstring | grep -o -E '\-*[0-9]+\.[0-9]*')
        linenum=$linenum+1
#crhf
        stabstring=$(grep -E 'RRHF.*CRHF' $logfile)
        crhf=$(echo $stabstring | grep -o -E '\-*[0-9]+\.[0-9]*')
#ruhf
        stabstring=$(grep -E 'RRHF.*RUHF' $logfile)
        ruhf=$(echo $stabstring | grep -o -E '\-*[0-9]+\.[0-9]*')
#write to file stable
        echo $alpha $y $rrhf $crhf $ruhf >> $hessfile

        estring=$(grep -E 'SCF Done:' $logfile)
        estring=$(echo $estring | grep -o -E '\-*[0-9]+\.[0-9]*')
        echo $alpha $y $estring >> $efile
        occmostring=$(grep -E 'Alpha  occ. eigenvalues' $logfile)
        occmostring=$(echo $occmostring | grep -o -E '\-*[0-9]+\.[0-9]*')
        occmo=($occmostring)
        virtmostring=$(grep -E 'Alpha virt. eigenvalues' $logfile)
        virtmostring=$(echo $virtmostring | grep -o -E '\-*[0-9]+\.[0-9]*')
        virtmo=($virtmostring)
	gap=$(echo ${virtmo[0]} - ${occmo[4]} | bc)
#        echo $alpha $y ${occmo[3]} ${occmo[4]} ${virtmo[0]} ${virtmo[1]} $gap >> $mofile
        echo $alpha $y ${occmo[@]} ${virtmo[@]} $gap >> $mofile

	cp $comfile 'com/'$comfile'_alpha'$alpha
	cp $logfile 'log/'$logfile'_alpha'$alpha


        usefinemesh=0
        for p in "${sigpts[@]}"
        do
# take abs val of the distance between y and p
                dist=$(echo $alpha - $p | bc)
                gt0=$(echo "$dist > 0.0" | bc -l)
                if [ $gt0 -eq 0 ] # if dist < 0, multiply by -1
                then
                        dist=$(bc <<< "scale=6; -1 *  $dist ")
                fi
                if [ $usefinemesh -eq 0 ] #only reset usefinemesh if it is 0/false. if true do not modify. 
                then
                        usefinemesh=$(echo "0.25 > $dist" | bc -l) #usefinemesh is 1/true if .1 > dist
                fi
        done
        if [ $usefinemesh -eq 1 ]
        then
                alpha=$(echo $alpha + $tinystep | bc)
        else
                alpha=$(echo $alpha + $step | bc)
        fi

#check if y is less than yi, if so keepgoing = 0, if not keepgoing = 1.
        keepgoing=$(echo "$alphaf > $alpha" | bc -l)
#end loop
done
