#!/bin/bash

declare -i number

numberstring=$(grep -n 'Summary' H4model.log)
number=$(echo $numberstring | grep -o -E '[0-9]+')
number=$number+20
echo '#n,r,scf,mp2,mp3' > fort.12
head -$number H4model.log | tail -18 > fort.12
